language: ruby
rvm:
- 2.2.2 
env:
  global:
    - secure: G7yT7Q+TOhPrCZU9F+MJ7juFrNEBC+TfA2AGrDmND+9Qp0HnibGMqHub8wJ5UeWPB0BgiE2ki0SUcKf+bBQiRbxFqY7TuPUhDXEoIE1nyHgSVrSJxCpBSbjSSUmCccKAepbfC2/P/MD9kCoqk2xqCziMHkejlngQx0nOaR6D5S8=
    - secure: eQsXR6ZB6ZGz3phNekZQS3Aa/UjuIIvfCy/DPrNduegaHMVNS9Jvrm/+4bPQ3JbzdWYg6kk+XHq4VACarap+zJGFCBBwtFfpCL0bzvcjiWK9mfb/yDBak6BSFASairRDObqEV9CGrj3y3iJhsX4VU/fuC5ia56Qnl6n6Kbupif0=

# before_script:
script: 
      - cd tests
      - ruby login_test.rb

addons:
  sauce_connect: true

# notifications:
#   hipchat: 2a07784c1aeed1b6efa332242d3fc3@Notifications
#   email: false
