language: ruby
rvm:
- 2.2.2 
env:
  global:
    - secure: frXcDuNPF1GFil2DeGx8dNQ+/Pw/IAsk8fr47KevY7+71flzFK79YwZyCxFJ034rvHclNNmnKorN96xia9YMoOP+EgMk9dZaQ4Hq7UmW5+DPjU4nfSlEz38CxVclHl9/KJvVyvQXV4vLuHOBEuj9cGoY/+lIjmpAyh/W8OTtZ4A=
    - secure: dvjFufJ+FmeI7DBbUW29qhSHq8B4qFWWol/My8sSPuhqtZk4Cviz96/LHLT1TqeAzf9TcBE5LjUrTlyK4FQOpqxwz2El/+4Wm6rsegDhWOe3v4ueZUb0ElTOvjDWLN412se42Y+9d/SX0OqcG77eOSFAQQcs/GV93APLCOUZUzY=


# before_script:
script: 
      - cd tests
      - ruby login_test.rb

addons:
  sauce_connect: true

# notifications:
#   hipchat: 2a07784c1aeed1b6efa332242d3fc3@Notifications
#   email: false
